version: "3.3"

networks:
  nmap-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.4.0.0/24  # Align subnet with IP addresses

services:
  # Angular Frontend (submodule)
  frontend:
    build:
      context: .
      dockerfile: ./nmap-frontend/Dockerfile
    
    volumes:
      - ./nmap-frontend:/usr/src/app
    
    ports:
      - 4200:4200

    networks:
      nmap-network:
        ipv4_address: 10.4.0.99  # Ensure this IP is within the subnet

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: ./nmap-backend/Dockerfile
    
    volumes:
      - ./nmap-backend:/app
    
    ports:
      - 8000:8000

    networks:
      nmap-network:
        ipv4_address: 10.4.0.100  # Ensure this IP is within the subnet